version: "3"
services:
  node:
    build: ./docker/node
    environment:
      - NODE_ENV=development
    volumes:
      - ./app/:/usr/src/app
    tty: true
    stdin_open: true
    ports:
      - "8080:8080"