version: "2"
services:
  node:
    build: ./node
    environment:
      - NODE_ENV=development
    volumes:
      - ./app/:/usr/src/app
    tty: true
    stdin_open: true
    ports:
      - "3000:3000"